### PR TITLE
Search by Phone Number and Email ID added

### PR DESCRIPTION
**Pull request by Prajwal2204**
You can now search for contact through email id and phone number (also corrected a missing comma while adding email to the csv file)

### CODE REVIEW

**Comment by sakshi2912** [comment]
@Prajwal2204 , could you please mention the issue you're trying to fix?

**Comment by Prajwal2204** [comment]
I added the search by phone number and email ID part

> @Prajwal2204 , could you please mention the issue you're trying to fix?

**Comment by Prajwal2204** [comment]
> @Prajwal2204 , could you please mention the issue you're trying to fix?

"Improve Search Function" to be precise

**Comment by sakshi2912** [comment]
> > @Prajwal2204 , could you please mention the issue you're trying to fix?
> 
> "Improve Search Function" to be precise

Cool! It works fine, I'll merge it.

**Comment by Prajwal2204** [comment]
thanks :)

**Comment by sakshi2912** [comment]
!bounty 50

**Comment by sakshi2912** [comment]
!bounty 65

**Pull request merged**
